name: Minecraft Server
description: minecraft server with itzg/minecraft-server
slug: minecraft_server
homeassistant_api: true
version: "1.0.0"
ports:
  25565/tcp: 25565
environment:
  EULA: "TRUE"
  DIFFICULTY: "{{ difficulty }}"
  GAMEMODE: "{{ gamemode }}"
  MAX_PLAYERS: "{{ max_players }}"
  MOTD: "{{ motd }}"
  MEMORY: "6G"
  SERVER_PORT: "{{ server_port }}"
options:
  difficulty: "normal"
  gamemode: "survival"
  max_players: 20
  motd: "Stierzunge"
  server_port: 25565
volumes:
  /data: {}
